site_name: "bash2gitlab"
site_url: "https://bash2gitlab.readthedocs.io/"
site_author: "Matthew Dean Martin <matthewdeanmartin@gmail.com>"
site_description: "Documentation of bash2gitlab, a tool for compiling bash to .gitlab-ci.yml"

repo_url: "https://github.com/matthewdeanmartin/bash2gitlab"

theme:
  name: readthedocs
  features:
    - navigation.footer

edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true

nav:
  - "Overview": "index.md"
  - "Installation": "installation.md"
  - "Usage":
      - "Usage": "usage.md"
      - "Configuration": "config.md"
      - "Commands": "commands.md"
      - "Workflows": "workflows.md"
  - "Level up your YAML + Bash":
      - "Formatting YAML": "formatting.md"
  - "API": "API.md"
  - "Prior Art":
      - "Keep Bash in Yaml": "PRIOR_ART.md"
  - "Change Log": "CHANGELOG.md"
  - "Contributing": "CONTRIBUTING.md"

validation:
  nav:
    omitted_files: warn
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6

plugins:
  - search
  - mkdocstrings