# pymarc - BSD-2-Clause

"stages":
  - "linting"
  - "tests"

"default":
  "image": "python:3.13-slim"

# linting is only done once with default image
"lint":
  "stage": "linting"
  "before_script": >-
    ./lint_before_script.sh
  "script": >-
    ./lint.sh
"test-coverage":
  "stage": "tests"
  "before_script": >-
    ./test-coverage_before_script.sh
  "script": >-
    ./test-coverage.sh
  "coverage": '/\d+\%\s*$/'
  "artifacts":
    "name": "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    "reports":
      "coverage_report":
        "coverage_format": "cobertura"
        "path": "coverage.xml"
    "when": "always"
    "expire_in": "1 day"

# run tests on other supported python versions
"test-python":
  "stage": "tests"
  "parallel":
    "matrix":
      - "PYTHON_VERSION": ['3.9', '3.10', '3.11', '3.12', '3.13']
  "image": "python:${PYTHON_VERSION}-slim"
  "before_script": >-
    ./test-python_before_script.sh
  "script": >-
    ./test-python.sh
